apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: vllm-server
  namespace: services-dev
spec:
  default:
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /DEV/vllm/health
  targetRef:
    group: ""
    kind: Service
    name: vllm-server