apiVersion: v1
kind: Service

metadata:
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"80":{}}}'
    meta.helm.sh/release-name: vllm-server
    meta.helm.sh/release-namespace: vllm-server
  generation: 6
  labels:
    app.kubernetes.io/instance: vllm-server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vllm-server
    app.kubernetes.io/version: 0.1.0
    helm.sh/chart: boilerplate-0.1.0
  name: vllm-server
  namespace: staging


spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: vllm-server
    app.kubernetes.io/name: vllm-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
